let SkillSet = [
  {title:".NET"},
  {title:".QL"},
  {title:"@Formula"},
  {title:"4th Dimension"},
  {title:"A-0 System"},
  {title:"A.NET"},
  {title:"A+"},
  {title:"ABAP"},
  {title:"ABC"},
  {title:"ABC ALGOL"},
  {title:"ACC"},
  {title:"Accent"},
  {title:"Ace DASL (Distributed Application Specification Language)"},
  {title:"Action!"},
  {title:"ActionScript"},
  {title:"Actor"},
  {title:"Ada"},
  {title:"Adabas D"},
  {title:"Adenine"},
  {title:"Agda"},
  {title:"Agilent VEE"},
  {title:"Agora"},
  {title:"AI"},
  {title:"AIMMS"},
  {title:"Airtable"},
  {title:"Aldor"},
  {title:"Alef"},
  {title:"ALF"},
  {title:"ALGOL 58"},
  {title:"ALGOL 60"},
  {title:"ALGOL 68"},
  {title:"ALGOL W"},
  {title:"Alice"},
  {title:"AllegroGraph"},
  {title:"Alma-0"},
  {title:"Altibase"},
  {title:"Amazon Aurora"},
  {title:"AmbientTalk"},
  {title:"Amiga E"},
  {title:"AMOS"},
  {title:"AMPL"},
  {title:"Android"},
  {title:"AngelScript"},
  {title:"Angular"},
  {title:"Ant"},
  {title:"Apache"},
  {title:"Apache Derby"},
  {title:"Apache Pig latin"},
  {title:"Apex"},
  {title:"APL"},
  {title:"App Inventor for Android's visual block language"},
  {title:"AppleScript"},
  {title:"APT"},
  {title:"AR"},
  {title:"ArangoDB"},
  {title:"Arc"},
  {title:"ARexx"},
  {title:"Argus"},
  {title:"Assembly language"},
  {title:"Aster Data"},
  {title:"AutoHotkey"},
  {title:"AutoIt"},
  {title:"AutoLISP / Visual LISP"},
  {title:"Averest"},
  {title:"AWK"},
  {title:"AWS"},
  {title:"Axum"},
  {title:"B"},
  {title:"Babbage"},
  {title:"Babel"},
  {title:"Backbone"},
  {title:"Ballerina"},
  {title:"BaseX"},
  {title:"Bash"},
  {title:"BASIC"},
  {title:"Batch file (Windows/MS-DOS)"},
  {title:"bc"},
  {title:"BCPL"},
  {title:"BeanShell"},
  {title:"Bertrand"},
  {title:"BETA"},
  {title:"Bitbucket"},
  {title:"BLISS"},
  {title:"Blockly"},
  {title:"BlooP"},
  {title:"Boo"},
  {title:"Boomerang"},
  {title:"Bootstrap"},
  {title:"Bosque"},
  {title:"Buddy"},
  {title:"C – ISO/IEC 9899"},
  {title:"C Shell (csh)"},
  {title:"C-- (C minus minus)"},
  {title:"C*"},
  {title:"C/AL"},
  {title:"C# (C sharp) – ISO/IEC 23270"},
  {title:"C++ (C plus plus) – ISO/IEC 14882"},
  {title:"CA Datacom"},
  {title:"CA IDMS"},
  {title:"Caché"},
  {title:"Caché ObjectScript"},
  {title:"CakePHP"},
  {title:"Caml"},
  {title:"Cayenne"},
  {title:"CDuce"},
  {title:"Cecil"},
  {title:"CEEMAC"},
  {title:"Cesil"},
  {title:"Céu"},
  {title:"Ceylon"},
  {title:"CFEngine"},
  {title:"Cg"},
  {title:"Ch"},
  {title:"Chapel"},
  {title:"Charm"},
  {title:"CHILL"},
  {title:"CHIP-8"},
  {title:"chomski"},
  {title:"ChucK"},
  {title:"Cilk"},
  {title:"CircleCI"},
  {title:"CL (IBM)"},
  {title:"Claire"},
  {title:"Clarion"},
  {title:"Clarion"},
  {title:"Clean"},
  {title:"ClickHouse"},
  {title:"Clipper"},
  {title:"CLIPS"},
  {title:"CLIST"},
  {title:"Clojure"},
  {title:"Cloudant"},
  {title:"CLU"},
  {title:"Clusterpoint Database"},
  {title:"Clustrix"},
  {title:"CMS EXEC (EXEC)"},
  {title:"CMS-2"},
  {title:"COBOL – ISO/IEC 1989"},
  {title:"CobolScript – COBOL Scripting language"},
  {title:"Cobra"},
  {title:"CockroachDB"},
  {title:"Codeship"},
  {title:"CoffeeScript"},
  {title:"ColdFusion"},
  {title:"COMAL"},
  {title:"Combined Programming Language (CPL)"},
  {title:"COMIT"},
  {title:"Common Intermediate Language (CIL)"},
  {title:"Common Lisp (also known as CL)"},
  {title:"COMPASS"},
  {title:"Component Pascal"},
  {title:"COMTRAN"},
  {title:"Constraint Handling Rules (CHR)"},
  {title:"Cool"},
  {title:"Coq"},
  {title:"Coral 66"},
  {title:"CorVision"},
  {title:"Cosmos DB"},
  {title:"Couchbase Server"},
  {title:"CouchDB"},
  {title:"COWSEL"},
  {title:"CPL"},
  {title:"CrateIO"},
  {title:"Cryptol"},
  {title:"Crystal"},
  {title:"Csound"},
  {title:"CSQL"},
  {title:"CSS"},
  {title:"CUBRID"},
  {title:"Cuneiform"},
  {title:"Curl"},
  {title:"Curry"},
  {title:"Cybil"},
  {title:"Cyclone"},
  {title:"Cypher Query Language"},
  {title:"Cython"},
  {title:"D"},
  {title:"Dart"},
  {title:"Darwin"},
  {title:"Data Science"},
  {title:"Database Management Library"},
  {title:"DataEase"},
  {title:"DataFlex"},
  {title:"DataFlex"},
  {title:"Datalog"},
  {title:"Dataphor"},
  {title:"DATATRIEVE"},
  {title:"DAX (Data Analysis Expressions)"},
  {title:"dBase"},
  {title:"dBase"},
  {title:"dc"},
  {title:"DCL"},
  {title:"Derby (aka Java DB)"},
  {title:"DIBOL"},
  {title:"DinkC"},
  {title:"Django"},
  {title:"Docker"},
  {title:"DocumentDB"},
  {title:"Dog"},
  {title:"Doppler"},
  {title:"Draco"},
  {title:"DRAKON"},
  {title:"Dylan"},
  {title:"DYNAMO"},
  {title:"E"},
  {title:"Ease"},
  {title:"Easy PL/I"},
  {title:"EASYTRIEVE PLUS"},
  {title:"eC"},
  {title:"ECMAScript"},
  {title:"Edinburgh IMP"},
  {title:"EGL"},
  {title:"Eiffel"},
  {title:"ELAN"},
  {title:"Elasticsearch"},
  {title:"Elixir"},
  {title:"Elm"},
  {title:"Emacs Lisp"},
  {title:"Ember"},
  {title:"Emerald"},
  {title:"Empress Embedded Database"},
  {title:"EnterpriseDB"},
  {title:"Epigram"},
  {title:"EPL (Easy Programming Language)"},
  {title:"EPL (Eltron Programming Language)"},
  {title:"Erlang"},
  {title:"es"},
  {title:"Escher"},
  {title:"ESPOL"},
  {title:"Esterel"},
  {title:"Etoys"},
  {title:"Euclid"},
  {title:"Euler"},
  {title:"Euphoria"},
  {title:"EusLisp Robot Programming Language"},
  {title:"Exasol"},
  {title:"EXEC 2"},
  {title:"Executable UML"},
  {title:"eXist"},
  {title:"Express"},
  {title:"eXtremeDB"},
  {title:"Ezhil"},
  {title:"F"},
  {title:"F-Script"},
  {title:"F*"},
  {title:"F#"},
  {title:"Factor"},
  {title:"Fantom"},
  {title:"FAUST"},
  {title:"FFP"},
  {title:"FileMaker Pro"},
  {title:"Firebase"},
  {title:"Firebird"},
  {title:"fish"},
  {title:"Fjölnir"},
  {title:"FL"},
  {title:"Flask"},
  {title:"Flavors"},
  {title:"Flex"},
  {title:"FlooP"},
  {title:"FLOW-MATIC"},
  {title:"FOCAL"},
  {title:"FOCUS"},
  {title:"FOIL"},
  {title:"FORMAC"},
  {title:"Forth"},
  {title:"Fortran – ISO/IEC 1539"},
  {title:"Fortress"},
  {title:"FP"},
  {title:"Franz Lisp"},
  {title:"FreeBasic"},
  {title:"FrontBase"},
  {title:"Futhark"},
  {title:"G-code"},
  {title:"Game Maker Language (Scripting language)"},
  {title:"GameMonkey Script"},
  {title:"GAMS"},
  {title:"GAP"},
  {title:"Gatsby"},
  {title:"GDL"},
  {title:"GDScript"},
  {title:"Genie"},
  {title:"GEORGE"},
  {title:"Git"},
  {title:"Github"},
  {title:"GitLab CI"},
  {title:"GLSL"},
  {title:"GNU E"},
  {title:"GNU Guile"},
  {title:"Go"},
  {title:"Go"},
  {title:"Go!"},
  {title:"GOAL"},
  {title:"Gödel"},
  {title:"Golo"},
  {title:"GOM (Good Old Mad)"},
  {title:"Google Apps Script"},
  {title:"Google Cloud"},
  {title:"Google Fusion Tables"},
  {title:"Gosu"},
  {title:"GOTRAN"},
  {title:"GPSS"},
  {title:"GraphTalk"},
  {title:"GRASS"},
  {title:"Grasshopper"},
  {title:"Greenplum"},
  {title:"Groovy"},
  {title:"GroveSite"},
  {title:"Grunt"},
  {title:"H2"},
  {title:"Hack"},
  {title:"HAGGIS"},
  {title:"HAL/S"},
  {title:"Halide (programming language)"},
  {title:"Hamilton C shell"},
  {title:"Harbour"},
  {title:"Hartmann pipelines"},
  {title:"Haskell"},
  {title:"Haxe"},
  {title:"Helix database"},
  {title:"Hermes"},
  {title:"Heroku"},
  {title:"High Level Assembly"},
  {title:"HLSL"},
  {title:"Hollywood"},
  {title:"HolyC"},
  {title:"Hop"},
  {title:"Hope"},
  {title:"Hopscotch"},
  {title:"HSQLDB"},
  {title:"HTML"},
  {title:"Hugo"},
  {title:"Hume"},
  {title:"HyperTalk"},
  {title:"IBM Basic assembly language"},
  {title:"IBM Business System 12 (historical)"},
  {title:"IBM DB2"},
  {title:"IBM DB2 Express-C"},
  {title:"IBM HAScript"},
  {title:"IBM Informix-4GL"},
  {title:"IBM Lotus Approach"},
  {title:"IBM RPG"},
  {title:"Icon"},
  {title:"IDL"},
  {title:"Idris"},
  {title:"Infobright"},
  {title:"Inform"},
  {title:"Informix"},
  {title:"Informix"},
  {title:"Ingres"},
  {title:"InterBase"},
  {title:"InterSystems Caché"},
  {title:"InterSystems IRIS Data Platform"},
  {title:"Io"},
  {title:"IOS"},
  {title:"J"},
  {title:"J#"},
  {title:"J++"},
  {title:"Jackrabbit"},
  {title:"JADE"},
  {title:"JAL"},
  {title:"Janus (concurrent constraint programming language)"},
  {title:"Janus (time-reversible computing programming language)"},
  {title:"JASS"},
  {title:"Java"},
  {title:"JavaFX Script"},
  {title:"JavaScript"},
  {title:"JCL"},
  {title:"JEAN"},
  {title:"Jenkins"},
  {title:"Jess (programming language)"},
  {title:"Join Java"},
  {title:"JOSS"},
  {title:"Joule"},
  {title:"JOVIAL"},
  {title:"Joy"},
  {title:"JQuery"},
  {title:"JScript"},
  {title:"JScript .NET"},
  {title:"Julia"},
  {title:"Jython"},
  {title:"K"},
  {title:"Kaleidoscope"},
  {title:"Karel"},
  {title:"KEE"},
  {title:"KIF"},
  {title:"Kixtart"},
  {title:"Klerer-May System"},
  {title:"Kodu"},
  {title:"Kojo"},
  {title:"Korn shell (ksh)"},
  {title:"Kotlin"},
  {title:"KRC"},
  {title:"KRL"},
  {title:"KRL (KUKA Robot Language)"},
  {title:"KRYPTON"},
  {title:"Kv"},
  {title:"LabVIEW"},
  {title:"Ladder"},
  {title:"Language H"},
  {title:"LANSA"},
  {title:"Laravel"},
  {title:"Lasso"},
  {title:"Lava"},
  {title:"LC-3"},
  {title:"Legoscript"},
  {title:"LibreOffice Base"},
  {title:"LIL"},
  {title:"LilyPond"},
  {title:"Limbo"},
  {title:"Limnor"},
  {title:"LINC"},
  {title:"Lingo"},
  {title:"LINQ"},
  {title:"Linter"},
  {title:"Linux"},
  {title:"LIS"},
  {title:"LISA"},
  {title:"Lisp – ISO/IEC 13816"},
  {title:"Lite-C"},
  {title:"Lithe"},
  {title:"Little b"},
  {title:"LiveCode"},
  {title:"LiveScript"},
  {title:"LLL"},
  {title:"Logo"},
  {title:"Logtalk"},
  {title:"Lotus Notes (IBM Lotus Domino)"},
  {title:"LotusScript"},
  {title:"LPC"},
  {title:"LSE"},
  {title:"LSL"},
  {title:"Lua"},
  {title:"Lucid"},
  {title:"Lustre"},
  {title:"LYaPAS"},
  {title:"Lynx"},
  {title:"M#"},
  {title:"M2001"},
  {title:"M4"},
  {title:"Mac OS"},
  {title:"Machine code"},
  {title:"Machine Learning"},
  {title:"MAD (Michigan Algorithm Decoder)"},
  {title:"MAD/I"},
  {title:"Magik"},
  {title:"Magma"},
  {title:"Máni"},
  {title:"Maple"},
  {title:"MAPPER (now part of BIS)"},
  {title:"MariaDB"},
  {title:"MARK-IV (now VISION:BUILDER)"},
  {title:"Markdown"},
  {title:"MarkLogic"},
  {title:"Mary"},
  {title:"MASM Microsoft Assembly x86"},
  {title:"MATH-MATIC"},
  {title:"MATLAB"},
  {title:"Maude system"},
  {title:"Max (Max Msp – Graphical Programming Environment)"},
  {title:"MaxDB"},
  {title:"Maxima (see also Macsyma)"},
  {title:"MaxScript internal language 3D Studio Max"},
  {title:"Maya (MEL)"},
  {title:"MDL"},
  {title:"MemSQL"},
  {title:"Mercury"},
  {title:"Mesa"},
  {title:"Meteor"},
  {title:"MHEG-5 (Interactive TV programming language)"},
  {title:"Microcode"},
  {title:"MicroScript"},
  {title:"Microsoft Access"},
  {title:"Microsoft Jet Database Engine (part of Microsoft Access)"},
  {title:"Microsoft SQL Server"},
  {title:"Microsoft SQL Server Express"},
  {title:"Microsoft Visual FoxPro"},
  {title:"MIIS"},
  {title:"Milk (programming language)"},
  {title:"Mimer SQL"},
  {title:"MIMIC"},
  {title:"Mirah"},
  {title:"Miranda"},
  {title:"MIVA Script"},
  {title:"ML"},
  {title:"Model 204"},
  {title:"Modelica"},
  {title:"Modula"},
  {title:"Modula-2"},
  {title:"Modula-3"},
  {title:"Mohol"},
  {title:"MonetDB"},
  {title:"MongoDB"},
  {title:"MongoDB"},
  {title:"MOO"},
  {title:"Mortran"},
  {title:"Mouse"},
  {title:"MPD"},
  {title:"MSL"},
  {title:"mSQL"},
  {title:"MUMPS"},
  {title:"MUMPS Database"},
  {title:"MuPAD"},
  {title:"Mutan"},
  {title:"MySQL"},
  {title:"Mystic Programming Language (MPL)"},
  {title:"Napier88"},
  {title:"NASM"},
  {title:"Neko"},
  {title:"Nemerle"},
  {title:"NESL"},
  {title:"Net.Data"},
  {title:"Netezza"},
  {title:"NetLogo"},
  {title:"NetRexx"},
  {title:"NewLISP"},
  {title:"NEWP"},
  {title:"Newspeak"},
  {title:"NewtonScript"},
  {title:"NexusDB"},
  {title:"Nial"},
  {title:"Nickle (NITIN)"},
  {title:"Nim"},
  {title:"Nix (Systems configuration language)"},
  {title:"NonStop SQL"},
  {title:"Node.js"},
  {title:"Not eXactly C (NXC)"},
  {title:"Not Quite C (NQC)"},
  {title:"NPL"},
  {title:"NSIS"},
  {title:"Nu"},
  {title:"NuoDB"},
  {title:"NWScript"},
  {title:"NXT-G"},
  {title:"o:XML"},
  {title:"Oak"},
  {title:"Oberon"},
  {title:"OBJ2"},
  {title:"Object Lisp"},
  {title:"Object Pascal"},
  {title:"Object REXX"},
  {title:"ObjectDatabase++"},
  {title:"Objective-C"},
  {title:"Objective-J"},
  {title:"ObjectLOGO"},
  {title:"Obliq"},
  {title:"OCaml"},
  {title:"occam"},
  {title:"occam-π"},
  {title:"Octave"},
  {title:"OmniMark"},
  {title:"Omnis Studio"},
  {title:"Opa"},
  {title:"Opal"},
  {title:"OpenCL"},
  {title:"OpenEdge ABL"},
  {title:"OpenLink Virtuoso"},
  {title:"OpenLink Virtuoso (Open Source Edition)"},
  {title:"OpenLink Virtuoso Universal Server"},
  {title:"OpenOffice.org Base"},
  {title:"OpenVera"},
  {title:"OPL"},
  {title:"OPS5"},
  {title:"OptimJ"},
  {title:"Oracle"},
  {title:"Oracle NoSQL Database"},
  {title:"Oracle Rdb for OpenVMS"},
  {title:"Orc"},
  {title:"ORCA/Modula-2"},
  {title:"Oriel"},
  {title:"OrientDB"},
  {title:"Orwell"},
  {title:"Oxygene"},
  {title:"Oz"},
  {title:"P"},
  {title:"P′′"},
  {title:"P4"},
  {title:"Panorama"},
  {title:"Paradox"},
  {title:"ParaSail (programming language)"},
  {title:"PARI/GP"},
  {title:"Pascal – ISO 7185"},
  {title:"Pascal Script"},
  {title:"PCASTL"},
  {title:"PCF"},
  {title:"PDL"},
  {title:"PEARL"},
  {title:"PeopleCode"},
  {title:"Percona Server for MySQL"},
  {title:"Percona XtraDB Cluster"},
  {title:"Perl"},
  {title:"Pervasive PSQL"},
  {title:"Pharo"},
  {title:"Phoenix"},
  {title:"PHP"},
  {title:"Pico"},
  {title:"Picolisp"},
  {title:"Pict"},
  {title:"Pike"},
  {title:"PILOT"},
  {title:"Pipelines"},
  {title:"Pizza"},
  {title:"PL-11"},
  {title:"PL/0"},
  {title:"PL/B"},
  {title:"PL/C"},
  {title:"PL/I – ISO 6160"},
  {title:"PL/M"},
  {title:"PL/P"},
  {title:"PL/SQL"},
  {title:"PL360"},
  {title:"PLANC"},
  {title:"Plankalkül"},
  {title:"Planner"},
  {title:"PLEX"},
  {title:"PLEXIL"},
  {title:"Plus"},
  {title:"Polyhedra"},
  {title:"POP-11"},
  {title:"POP-2"},
  {title:"PortablE"},
  {title:"Postgres Plus Advanced Server"},
  {title:"PostgreSQL"},
  {title:"PostgreSQL"},
  {title:"Postman"},
  {title:"PostScript"},
  {title:"POV-Ray SDL"},
  {title:"PowerBuilder – 4GL GUI application generator from Sybase"},
  {title:"Powerhouse"},
  {title:"PowerShell"},
  {title:"PPL"},
  {title:"Pro*C"},
  {title:"Processing"},
  {title:"Processing.js"},
  {title:"Prograph"},
  {title:"Progress Software"},
  {title:"PROIV"},
  {title:"Prolog"},
  {title:"PROMAL"},
  {title:"Promela"},
  {title:"PROSE modeling language"},
  {title:"PROTEL"},
  {title:"ProvideX"},
  {title:"Pure"},
  {title:"Pure Data"},
  {title:"PureScript"},
  {title:"Python"},
  {title:"Q (programming language from Kx Systems)"},
  {title:"Q# (Microsoft programming language)"},
  {title:"Qalb"},
  {title:"Qizx"},
  {title:"QPL"},
  {title:"QtScript"},
  {title:"QuakeC"},
  {title:"Quantum Computation Language"},
  {title:"R"},
  {title:"R:Base"},
  {title:"R++"},
  {title:"Racket"},
  {title:"Raima Database Manager (RDM)"},
  {title:"Raku"},
  {title:"RAPID"},
  {title:"Rapira"},
  {title:"Ratfiv"},
  {title:"Ratfor"},
  {title:"rc"},
  {title:"RDM Server"},
  {title:"React"},
  {title:"React Native"},
  {title:"Reason"},
  {title:"REBOL"},
  {title:"Red"},
  {title:"Redcode"},
  {title:"REFAL"},
  {title:"ReJSON[21]"},
  {title:"RethinkDB"},
  {title:"RethinkDB"},
  {title:"REXX"},
  {title:"Rlab"},
  {title:"ROOP"},
  {title:"RPG"},
  {title:"RPL"},
  {title:"RSL"},
  {title:"RTL/2"},
  {title:"Ruby"},
  {title:"Ruby on Rails"},
  {title:"Rust"},
  {title:"S"},
  {title:"S-Lang"},
  {title:"S-PLUS"},
  {title:"S/SL"},
  {title:"S2"},
  {title:"S3"},
  {title:"SA-C"},
  {title:"SabreTalk"},
  {title:"SAIL"},
  {title:"SAND CDBMS"},
  {title:"SAP Adaptive Server Enterprise"},
  {title:"SAP Advantage Database Server(formerly known as Sybase Advantage Database Server)"},
  {title:"SAP HANA"},
  {title:"SAP HANA"},
  {title:"SAP IQ (formerly known as Sybase IQ)"},
  {title:"SAS"},
  {title:"SASL"},
  {title:"Sass"},
  {title:"Sather"},
  {title:"Sawzall"},
  {title:"SBL"},
  {title:"Scala"},
  {title:"Scheme"},
  {title:"Scilab"},
  {title:"Scratch"},
  {title:"Script.NET"},
  {title:"Sed"},
  {title:"Sedna"},
  {title:"Seed7"},
  {title:"Self"},
  {title:"Semaphore"},
  {title:"SenseTalk"},
  {title:"SequenceL"},
  {title:"Serpent"},
  {title:"SETL"},
  {title:"Shell Scripting"},
  {title:"SIGNAL"},
  {title:"SiMPLE"},
  {title:"SimpleDB"},
  {title:"SIMPOL"},
  {title:"SIMSCRIPT"},
  {title:"Simula"},
  {title:"Simulink"},
  {title:"Singularity"},
  {title:"SISAL"},
  {title:"SLIP"},
  {title:"SMALL"},
  {title:"Smalltalk"},
  {title:"SML"},
  {title:"Snap!"},
  {title:"SNOBOL (SPITBOL)"},
  {title:"Snowball"},
  {title:"Snowflake Cloud Data Warehouse"},
  {title:"SOL"},
  {title:"solidDB"},
  {title:"Solidity"},
  {title:"Solr"},
  {title:"SOPHAEROS"},
  {title:"Source"},
  {title:"SP/k"},
  {title:"SPARK"},
  {title:"Speakeasy"},
  {title:"Speedcode"},
  {title:"SPIN"},
  {title:"Spring Boot"},
  {title:"SPS"},
  {title:"SQL"},
  {title:"SQL Anywhere (formerly known as Sybase Adaptive Server Anywhere and Watcom SQL)"},
  {title:"SQL Azure (Cloud SQL Server)"},
  {title:"SQLBase"},
  {title:"SQLite"},
  {title:"SQR"},
  {title:"SQream DB"},
  {title:"Squeak"},
  {title:"Squirrel"},
  {title:"SR"},
  {title:"Starlogo"},
  {title:"Stata"},
  {title:"Stateflow"},
  {title:"Strand"},
  {title:"Strongtalk"},
  {title:"Subtext"},
  {title:"SuperCollider"},
  {title:"SuperTalk"},
  {title:"Swift (Apple programming language)"},
  {title:"Swift (parallel scripting language)"},
  {title:"SYMPL"},
  {title:"SystemVerilog"},
  {title:"T"},
  {title:"T-SQL"},
  {title:"TACL"},
  {title:"TACPOL"},
  {title:"TADS"},
  {title:"Tailwind"},
  {title:"TAL"},
  {title:"Tcl"},
  {title:"Tea"},
  {title:"TeamCity"},
  {title:"TECO"},
  {title:"TELCOMP"},
  {title:"Teradata"},
  {title:"TeX"},
  {title:"TEX"},
  {title:"TeX"},
  {title:"Tibero"},
  {title:"TiDB"},
  {title:"TIE"},
  {title:"TimesTen"},
  {title:"TMG, compiler-compiler"},
  {title:"Toi"},
  {title:"TokuMX"},
  {title:"Tom"},
  {title:"Topspeed"},
  {title:"TPU"},
  {title:"Trac"},
  {title:"Trafodion"},
  {title:"Transcript"},
  {title:"Travis"},
  {title:"TTCN"},
  {title:"TTM"},
  {title:"Turing"},
  {title:"TUTOR"},
  {title:"TXL"},
  {title:"Tynker"},
  {title:"TypeScript"},
  {title:"Ubercode"},
  {title:"UCSD Pascal"},
  {title:"Umple"},
  {title:"Unicon"},
  {title:"UniData"},
  {title:"Uniface"},
  {title:"Unisys RDMS 2200"},
  {title:"UNITY"},
  {title:"UniVerse"},
  {title:"Unix shell"},
  {title:"UnrealScript"},
  {title:"Vala"},
  {title:"Vectorwise"},
  {title:"Verilog"},
  {title:"Vertica"},
  {title:"VHDL"},
  {title:"Vim script"},
  {title:"Viper"},
  {title:"Visual DataFlex"},
  {title:"Visual DialogScript"},
  {title:"Visual FoxPro"},
  {title:"Visual J++"},
  {title:"Visual LISP"},
  {title:"Visual Objects"},
  {title:"Visual Prolog"},
  {title:"VoltDB"},
  {title:"VR"},
  {title:"Vue"},
  {title:"WATFIV, WATFOR"},
  {title:"WebAssembly"},
  {title:"WebDNA"},
  {title:"Webpack"},
  {title:"Wercker"},
  {title:"Whiley"},
  {title:"Winbatch"},
  {title:"Windows"},
  {title:"Wolfram Language"},
  {title:"Wyvern"},
  {title:"X++"},
  {title:"X10"},
  {title:"xBase"},
  {title:"xBase++"},
  {title:"XBL"},
  {title:"XC (targets XMOS architecture)"},
  {title:"xHarbour"},
  {title:"XHTML"},
  {title:"XL"},
  {title:"XML"},
  {title:"Xod"},
  {title:"Xojo"},
  {title:"XOTcl"},
  {title:"XPL"},
  {title:"XPL0"},
  {title:"XQuery"},
  {title:"XSB"},
  {title:"XSharp"},
  {title:"XSL"},
  {title:"XSLT"},
  {title:"Xtend"},
  {title:"YAML"},
  {title:"Yoix"},
  {title:"Yorick"},
  {title:"YQL"},
  {title:"YugabyteDB"},
  {title:"YUI"},
  {title:"Z notation"},
  {title:"Z++"},
  {title:"Zeno"},
  {title:"ZetaLisp"},
  {title:"Zig"},
  {title:"ZOPL"},
  {title:"ZPL"},
  {title:"Just Joined!"}
];

export default SkillSet;